import { useEffect, useState } from "react";
import { LockKeyhole, MessageCircle, Send, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type MessagesWorkspaceProps = { user: any; isAuthenticated: boolean; requestedUserId?: number | null; onLogin: () => void };

export default function MessagesWorkspace({ user, isAuthenticated, requestedUserId, onLogin }: MessagesWorkspaceProps) {
  const [conversationId, setConversationId] = useState<number | null>(null);
  const [draft, setDraft] = useState("");
  const conversations = trpc.dm.conversations.useQuery(undefined, { enabled: isAuthenticated });
  const messages = trpc.dm.messages.useQuery({ conversationId: conversationId ?? 0 }, { enabled: isAuthenticated && conversationId !== null, refetchInterval: 15000 });
  const start = trpc.dm.start.useMutation({ onSuccess: data => { if (data?.id) { setConversationId(data.id); conversations.refetch(); } }, onError: error => toast.error(error.message) });
  const send = trpc.dm.send.useMutation({ onSuccess: () => { setDraft(""); messages.refetch(); conversations.refetch(); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (requestedUserId && isAuthenticated) start.mutate({ userId: requestedUserId }); }, [requestedUserId, isAuthenticated]);
  if (!isAuthenticated) return <div className="empty-state panel-card"><LockKeyhole size={28} /><h3>الرسائل الخاصة للأعضاء فقط</h3><p>سجّل الدخول بحساب Google لبدء محادثة محمية.</p><button className="primary-button" onClick={onLogin}>تسجيل الدخول</button></div>;
  const sendMessage = () => { if (conversationId && draft.trim()) send.mutate({ conversationId, content: draft.trim() }); };
  return <section className="messages-layout"><div className="messages-sidebar panel-card"><div className="section-tag">// محادثاتك</div><h3>رسائل خاصة</h3><div className="privacy-note"><ShieldCheck size={15} /><span>مشفرة في التخزين ولا يراها إلا أطراف المحادثة أو Admin المخول.</span></div>{conversations.isLoading ? <p className="muted-cell">جارٍ تحميل المحادثات...</p> : conversations.data?.length ? conversations.data.map(conversation => <button className={`conversation-row ${conversationId === conversation.id ? "active" : ""}`} key={conversation.id} onClick={() => setConversationId(conversation.id)}><div className="post-avatar small">{conversation.peer?.avatarUrl ? <img src={conversation.peer.avatarUrl} alt="" /> : conversation.peer?.name?.[0] ?? "C"}</div><div><strong>{conversation.peer?.name ?? "عضو غير متاح"}</strong><span>{conversation.lastMessageAt ? new Date(conversation.lastMessageAt).toLocaleString("ar-EG") : "محادثة جديدة"}</span></div></button>) : <div className="empty-state"><MessageCircle size={22} /><p>ابدأ رسالة من صفحة المجتمع.</p></div>}</div><div className="message-thread panel-card">{conversationId ? <><div className="thread-head"><div><div className="section-tag">// قناة خاصة</div><h3>محادثة CyberJocx</h3></div><LockKeyhole size={17} /></div><div className="thread-messages">{messages.isLoading ? <p className="muted-cell">جارٍ فك الرسائل المصرح بها...</p> : messages.data?.length ? messages.data.map(message => <div className={`thread-bubble ${message.senderId === user?.id ? "mine" : "theirs"}`} key={message.id}><p>{message.content}</p><span>{new Date(message.createdAt).toLocaleString("ar-EG")}</span></div>) : <div className="empty-state"><MessageCircle size={22} /><p>اكتب أول رسالة في هذه المحادثة.</p></div>}</div><div className="thread-composer"><textarea value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); sendMessage(); } }} placeholder="اكتب رسالة خاصة..." /><button className="primary-button compact" onClick={sendMessage} disabled={!draft.trim() || send.isPending}><Send size={15} /> إرسال</button></div></> : <div className="empty-state"><UserRound size={28} /><h3>اختر محادثة</h3><p>الرسائل لا تظهر في المجتمع العام.</p></div>}</div></section>;
}
